import { TagColor, TagPattern } from "@prisma/client";
import type { TagProps } from "~/ui/Tag/types";

export const TAG_LABEL = {
  [TagColor.RED]: "Red",
  [TagColor.BLUE]: "Blue",
  [TagColor.GRAY]: "Gray",
  [TagColor.PINK]: "Pink",
  [TagColor.PUCE]: "Puce",
  [TagColor.BROWN]: "Brown",
  [TagColor.GREEN]: "Green",
  [TagColor.SMALT]: "Smalt",
  [TagColor.BISQUE]: "Bisque",
  [TagColor.DAMASK]: "Damask",
  [TagColor.JASPER]: "Jasper",
  [TagColor.ORANGE]: "Orange",
  [TagColor.PURPLE]: "Purple",
  [TagColor.TITIAN]: "Titian",
  [TagColor.VIOLET]: "Violet",
  [TagColor.YELLOW]: "Yellow",
  [TagColor.CATTLEYA]: "Cattleya",
  [TagColor.BITTERSWEET]: "Bittersweet",
  [TagPattern.WAVY]: "Wavy",
  [TagPattern.OMBRE]: "Ombre",
  [TagPattern.PLAID]: "Plaid",
  [TagPattern.DOTTED]: "Dotted",
  [TagPattern.FLORAL]: "Floral",
  [TagPattern.ZIGZAG]: "Zigzag",
  [TagPattern.CHEVRON]: "Chevron",
  [TagPattern.CIRCLES]: "Circles",
  [TagPattern.DIAMOND]: "Diamond",
  [TagPattern.LATTICE]: "Lattice",
  [TagPattern.PAISLEY]: "Paisley",
  [TagPattern.ROUNDED]: "Rounded",
  [TagPattern.STRIPED]: "Striped",
  [TagPattern.GEOMETRIC]: "Geometric",
  [TagPattern.BASKETWEAVE]: "Basketweave",
} satisfies Record<TagProps['name'], string>;

export const TAG_COLOR_OPTIONS = [
  { label: TAG_LABEL[TagColor.RED], value: TagColor.RED },
  { label: TAG_LABEL[TagColor.BLUE], value: TagColor.BLUE },
  { label: TAG_LABEL[TagColor.GRAY], value: TagColor.GRAY },
  { label: TAG_LABEL[TagColor.PINK], value: TagColor.PINK },
  { label: TAG_LABEL[TagColor.PUCE], value: TagColor.PUCE },
  { label: TAG_LABEL[TagColor.BROWN], value: TagColor.BROWN },
  { label: TAG_LABEL[TagColor.GREEN], value: TagColor.GREEN },
  { label: TAG_LABEL[TagColor.SMALT], value: TagColor.SMALT },
  { label: TAG_LABEL[TagColor.BISQUE], value: TagColor.BISQUE },
  { label: TAG_LABEL[TagColor.DAMASK], value: TagColor.DAMASK },
  { label: TAG_LABEL[TagColor.JASPER], value: TagColor.JASPER },
  { label: TAG_LABEL[TagColor.ORANGE], value: TagColor.ORANGE },
  { label: TAG_LABEL[TagColor.PURPLE], value: TagColor.PURPLE },
  { label: TAG_LABEL[TagColor.TITIAN], value: TagColor.TITIAN },
  { label: TAG_LABEL[TagColor.VIOLET], value: TagColor.VIOLET },
  { label: TAG_LABEL[TagColor.YELLOW], value: TagColor.YELLOW },
  { label: TAG_LABEL[TagColor.CATTLEYA], value: TagColor.CATTLEYA },
  { label: TAG_LABEL[TagColor.BITTERSWEET], value: TagColor.BITTERSWEET },
];

export const TAG_PATTERN_OPTIONS = [
  { label: TAG_LABEL[TagPattern.WAVY], value: TagPattern.WAVY },
  { label: TAG_LABEL[TagPattern.OMBRE], value: TagPattern.OMBRE },
  { label: TAG_LABEL[TagPattern.PLAID], value: TagPattern.PLAID },
  { label: TAG_LABEL[TagPattern.DOTTED], value: TagPattern.DOTTED },
  { label: TAG_LABEL[TagPattern.FLORAL], value: TagPattern.FLORAL },
  { label: TAG_LABEL[TagPattern.ZIGZAG], value: TagPattern.ZIGZAG },
  { label: TAG_LABEL[TagPattern.CHEVRON], value: TagPattern.CHEVRON },
  { label: TAG_LABEL[TagPattern.CIRCLES], value: TagPattern.CIRCLES },
  { label: TAG_LABEL[TagPattern.DIAMOND], value: TagPattern.DIAMOND },
  { label: TAG_LABEL[TagPattern.LATTICE], value: TagPattern.LATTICE },
  { label: TAG_LABEL[TagPattern.PAISLEY], value: TagPattern.PAISLEY },
  { label: TAG_LABEL[TagPattern.ROUNDED], value: TagPattern.ROUNDED },
  { label: TAG_LABEL[TagPattern.STRIPED], value: TagPattern.STRIPED },
  { label: TAG_LABEL[TagPattern.GEOMETRIC], value: TagPattern.GEOMETRIC },
  { label: TAG_LABEL[TagPattern.BASKETWEAVE], value: TagPattern.BASKETWEAVE },
];
